name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: debugging 
        run: |
          pwd
          ls -la

      - name: Navigating to project directory
        run: cd /home/runner/work/docs-german-translator/mysimpleGPTBot

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.22.12'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, xml, zip, pdo, pdo_mysql
          composer-version: '2.6.4'
          ini-values: |
            memory_limit=-1
            post_max_size=512M
            upload_max_filesize=512M

      - name: Install Composer dependencies
        run: composer install --no-interaction --optimize-autoloader

      - name: Install NPM dependencies and compile assets
        run: |
          npm install
          npm run production

      - name: Create .env file
        run: cp .env.example .env
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: laravel
          DB_PASSWORD: secret

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

      - name: Optimize Laravel for production
        run: php artisan optimize --force

      - name: Clear caches
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear

      # You can add more steps here if needed, such as restarting your web server
      #
      - name: Build process completed successfully
        run: echo "Build process completed successfully."
      #
